tap "scstubblefield/personal"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "boost"
brew "coreutils"
brew "git"
brew "python"
brew "gnupg"
brew "go"
brew "graphviz"
brew "imagemagick"
brew "inetutils"
brew "jq"
brew "mas"
brew "mysql@5.7", restart_service: true, link: true
brew "nethack"
brew "nodenv"
brew "postgresql"
brew "rbenv"
brew "redis", restart_service: true
brew "rustup-init"
brew "streamlink"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "uudeview"
brew "vim"
brew "watch"
brew "weechat"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "scstubblefield/personal/wit"
brew "heroku/brew/heroku"
cask "apple-hewlett-packard-printer-drivers"
cask "battle-net"
cask "chromedriver"
cask "cyberduck"
cask "dash"
cask "discord"
cask "docker"
cask "dolphin"
cask "font-anonymous-pro"
cask "font-fira-mono"
cask "font-inconsolata"
cask "font-meslo-lg"
cask "font-source-code-pro"
cask "font-terminus"
cask "google-backup-and-sync"
cask "google-chrome"
cask "macdown"
cask "ngrok"
cask "openemu"
cask "postman"
cask "sejda-pdf"
cask "sequel-pro"
cask "slack"
cask "spectacle"
cask "the-unarchiver"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
